[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
kapora = "AkQXPVXUYDqyNUVNAsYGYXy9sHQR636xcuJbAJkiJe5F"

[programs.devnet]
kapora = "AkQXPVXUYDqyNUVNAsYGYXy9sHQR636xcuJbAJkiJe5F"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm test"
